/* Use it as the node in the BST MyMap
 * DO NOT edit this file.
 */

#ifndef TREENODE_H
#define TREENODE_H

template <typename T>
struct TreeNode
{
    T data;
    TreeNode *left;
    TreeNode *right;
    TreeNode(const T &x, TreeNode *lc, TreeNode *rc):data(x), left(lc),
      right(rc) {}
};

#endif
